# Generated by Django 5.2.4 on 2025-07-13 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('porcentaje_descuento', models.FloatField()),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
            },
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='entidades/')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre_servicio_a', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('importes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_socio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Mas_informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.TextField()),
            ],
            options={
                'verbose_name': 'Más Información',
                'verbose_name_plural': 'Más Información',
            },
        ),
        migrations.CreateModel(
            name='Subservicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='subservicios/')),
            ],
            options={
                'verbose_name': 'Subservicio',
                'verbose_name_plural': 'Subservicios',
            },
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_seguro_vida', models.BooleanField(default=False)),
                ('f_inscripcion', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('socio', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('ubicacion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asociados', to='camara_app.beneficio')),
                ('id_mas_informacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='camara_app.mas_informacion')),
                ('id_subservicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='camara_app.subservicios')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to=settings.AUTH_USER_MODEL)),
                ('id_servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='camara_app.servicios')),
            ],
            options={
                'verbose_name': 'Selección',
                'verbose_name_plural': 'Selecciones',
            },
        ),
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('descuento', models.FloatField(default=0.0)),
                ('precio_convenido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='camara_app.entidades')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='camara_app.servicios')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='camara_app.servicios')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
