# Generated by Django 5.2.4 on 2025-07-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
