# Generated by Django 5.2.4 on 2025-07-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0002_perfilusuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiarioSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje del seguro (ej. 50.00)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Beneficiario de Seguro',
                'verbose_name_plural': 'Beneficiarios de Seguro',
            },
        ),
        migrations.RenameField(
            model_name='formularios',
            old_name='f_inscripcion',
            new_name='f_socio',
        ),
        migrations.AddField(
            model_name='factura',
            name='id_perfil_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='camara_app.perfilusuario'),
        ),
        migrations.CreateModel(
            name='InformacionSeguroSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=255)),
                ('telefono_titular', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento_titular', models.DateField(blank=True, null=True)),
                ('cedula_titular', models.CharField(max_length=10)),
                ('firma_titular', models.CharField(blank=True, help_text='Nombre completo para firma de aceptación', max_length=255, null=True)),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_seguro', to='camara_app.beneficiarioseguro')),
            ],
            options={
                'verbose_name': 'Información de Seguro del Socio',
                'verbose_name_plural': 'Información de Seguros de Socios',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, help_text='Razón Social (para personas jurídicas)', max_length=255, null=True)),
                ('nombre_comercial', models.CharField(help_text='Nombre Comercial (empresa) o Nombres y Apellidos (persona natural)', max_length=255)),
                ('ruc_cedula', models.CharField(help_text='RUC (13 dígitos) o Cédula (10 dígitos)', max_length=13, unique=True)),
                ('email_principal', models.EmailField(help_text='Correo electrónico principal del socio/empresa', max_length=254, unique=True)),
                ('redes_sociales', models.CharField(blank=True, help_text='Redes sociales que utiliza (separadas por comas)', max_length=255, null=True)),
                ('cedula_representante', models.CharField(blank=True, help_text='Cédula o Pasaporte del Representante Legal', max_length=10, null=True)),
                ('apellidos_nombres_representante', models.CharField(blank=True, help_text='Apellidos y Nombres del Representante Legal', max_length=255, null=True)),
                ('direccion_principal', models.CharField(help_text='Dirección principal del negocio', max_length=255)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('interseccion', models.CharField(blank=True, help_text='Calle de intersección', max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, help_text='Referencia de la dirección', max_length=255, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(default='Loja', max_length=100)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('pagina_web', models.URLField(blank=True, null=True)),
                ('email_empresa', models.EmailField(blank=True, help_text='Correo electrónico de la empresa (si es diferente al principal)', max_length=254, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_negocio', models.CharField(blank=True, choices=[('Comercio', 'Comercio'), ('Servicios', 'Servicios'), ('Importación/Exportación', 'Importación/Exportación'), ('Industria', 'Industria'), ('Otros', 'Otros')], help_text='Tipo principal de negocio (ej. Comercio, Servicios). Puede ser expandido a ManyToMany si aplica varios.', max_length=100, null=True)),
                ('actividad_especifica', models.TextField(blank=True, help_text='Descripción específica de la actividad económica', null=True)),
                ('representante_contacto', models.CharField(blank=True, help_text='Nombre del Representante Legal (para contacto)', max_length=255, null=True)),
                ('propietario_contacto', models.CharField(blank=True, help_text='Nombre del Propietario/Dueño (para contacto - personas naturales)', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el socio está activo')),
                ('id_seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='camara_app.informacionsegurosocio')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.AddField(
            model_name='servicios',
            name='id_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='camara_app.socio'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='camara_app.socio'),
        ),
    ]
