# Generated by Django 5.2.4 on 2025-07-20 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0003_beneficiarioseguro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('estatura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estatura (cm)')),
                ('tension_arterial_sistolica', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tensión Arterial Sistólica')),
                ('tension_arterial_diastolica', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tensión Arterial Diastólica')),
                ('peso_ha_cambiado', models.BooleanField(default=False, verbose_name='¿Su peso ha aumentado o disminuido durante el último año?')),
                ('cuanto_peso_cambio', models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Cuánto peso cambió?')),
                ('peso_cambio_intencional', models.BooleanField(default=False, verbose_name='¿Cambio de peso intencional?')),
                ('causa_peso_cambio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Causa del cambio de peso')),
                ('pregunta1_salud', models.BooleanField(default=False, verbose_name='1. ¿Afecciones del corazón o aparato circulatorio...?')),
                ('pregunta2_salud', models.BooleanField(default=False, verbose_name='2. ¿Afecciones de los órganos respiratorios...?')),
                ('pregunta3_salud', models.BooleanField(default=False, verbose_name='3. ¿Enfermedad circulatoria o accidente vascular cerebral?')),
                ('pregunta4_salud', models.BooleanField(default=False, verbose_name='4. ¿Enfermedades del sistema endocrino...?')),
                ('pregunta5_salud', models.BooleanField(default=False, verbose_name='5. ¿Cirrosis hepática, hepatitis C o insuficiencia hepática?')),
                ('pregunta6_salud', models.BooleanField(default=False, verbose_name='6. ¿Edema o supuración o aumento de volumen de los ganglios linfáticos?')),
                ('pregunta7_salud', models.BooleanField(default=False, verbose_name='7. Afecciones del cerebro o del sistema nervioso...?')),
                ('pregunta8_salud', models.BooleanField(default=False, verbose_name='8. Afecciones del aparato digestivo...?')),
                ('pregunta9_salud', models.BooleanField(default=False, verbose_name='9. ¿Enfermedades de la piel?')),
                ('pregunta10_salud', models.BooleanField(default=False, verbose_name='10. ¿Enfermedades infecciosas...?')),
                ('consume_alcohol', models.BooleanField(default=False, verbose_name='¿Consume usted bebidas alcohólicas?')),
                ('cuales_alcohol', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuáles bebidas alcohólicas?')),
                ('cuanto_diariamente_alcohol', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuánto alcohol diariamente?')),
                ('uso_estupefacientes', models.BooleanField(default=False, verbose_name='¿Hace o ha hecho uso de estupefacientes?')),
                ('cuales_estupefacientes', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuáles estupefacientes?')),
                ('hasta_cuando_estupefacientes', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Hasta cuándo estupefacientes?')),
                ('toma_anticonceptivos', models.BooleanField(default=False, verbose_name='¿Toma Usted anticonceptivos?')),
                ('esta_embarazada', models.BooleanField(default=False, verbose_name='¿Está usted embarazada?')),
                ('cuantos_meses_embarazo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='¿Cuántos meses de embarazo?')),
                ('enfermedad_ginecologica', models.BooleanField(default=False, verbose_name='¿Ha sufrido alguna enfermedad ginecológica?')),
                ('medico_cabecera', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Quién es su médico de cabecera?')),
                ('medico_ultima_vez', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Quién es el médico que le ha tratado por última vez?')),
                ('cuando_ultima_vez', models.DateField(blank=True, null=True, verbose_name='¿Cuándo fue la última vez que le trató un médico?')),
                ('motivo_ultima_vez', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de la última consulta médica')),
                ('otra_declaracion_salud', models.TextField(blank=True, null=True, verbose_name='¿Tiene Usted alguna otra cosa que declarar sobre su salud? Indique:')),
            ],
            options={
                'verbose_name': 'Declaración de Salud',
                'verbose_name_plural': 'Declaraciones de Salud',
            },
        ),
        migrations.CreateModel(
            name='SolicitudSeguroVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC')], default='cedula', max_length=10, verbose_name='Tipo de identificación')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de identificación')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20, null=True, verbose_name='Estado Civil')),
                ('direccion_domicilio', models.CharField(max_length=255, verbose_name='Dirección Domicilio')),
                ('correo_domicilio', models.EmailField(max_length=100, verbose_name='Correo Electrónico Domicilio')),
                ('telefono_domicilio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Domicilio')),
                ('celular_domicilio', models.CharField(max_length=20, verbose_name='Celular Domicilio')),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la empresa')),
                ('direccion_trabajo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Trabajo')),
                ('correo_trabajo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico Trabajo')),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Trabajo')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('envio_correspondencia', models.CharField(blank=True, choices=[('domicilio', 'Domicilio'), ('trabajo', 'Trabajo')], max_length=10, null=True, verbose_name='Envío de correspondencia')),
                ('otros_seguros_vida', models.BooleanField(default=False, verbose_name='¿Tiene o está tramitando otros seguros de vida?')),
                ('especifique_companias_otros_seguros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especifique compañías de otros seguros')),
                ('es_usted', models.CharField(blank=True, choices=[('titular', 'Titular'), ('beneficiario', 'Beneficiario')], max_length=20, null=True, verbose_name='Es usted')),
                ('lugar_firma', models.CharField(max_length=100, verbose_name='Lugar de Firma')),
                ('fecha_firma', models.DateField(auto_now_add=True, verbose_name='Fecha de Firma')),
                ('firma_electronica_generada', models.BooleanField(default=False, verbose_name='¿Firma electrónica generada?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Seguro de Vida',
                'verbose_name_plural': 'Solicitudes de Seguro de Vida',
            },
        ),
        migrations.AlterField(
            model_name='informacionsegurosocio',
            name='id_beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informacion_seguro', to='camara_app.beneficiarioseguro'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id_seguro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios', to='camara_app.informacionsegurosocio'),
        ),
        migrations.CreateModel(
            name='DetalleDeclaracionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pregunta', models.PositiveSmallIntegerField(verbose_name='Nro de pregunta')),
                ('detalle', models.TextField(verbose_name='Detalle de la afección')),
                ('cuando', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuándo ocurrió?')),
                ('duracion', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Duración?')),
                ('secuelas', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Secuelas?')),
                ('medico_tratante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre y dirección del médico tratante')),
                ('declaracion_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_preguntas_salud', to='camara_app.declaracionsalud', verbose_name='Declaración de Salud')),
            ],
            options={
                'verbose_name': 'Detalle de Declaración de Salud',
                'verbose_name_plural': 'Detalles de Declaración de Salud',
            },
        ),
        migrations.CreateModel(
            name='DeporteActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=255, verbose_name='¿Qué deportes y/o actividades recreacionales practica?')),
                ('con_competicion', models.BooleanField(default=False, verbose_name='¿Con competición?')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deportes_actividades', to='camara_app.solicitudsegurovida', verbose_name='Solicitud de Seguro')),
            ],
            options={
                'verbose_name': 'Deporte o Actividad Recreacional',
                'verbose_name_plural': 'Deportes y Actividades Recreacionales',
            },
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaracion_salud', to='camara_app.solicitudsegurovida', verbose_name='Solicitud de Seguro'),
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.CharField(max_length=255, verbose_name='Nombres completos')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('parentesco', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('cedula_identidad', models.CharField(max_length=20, verbose_name='C.I.')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje (%)')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='camara_app.solicitudsegurovida', verbose_name='Solicitud de Seguro')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='camara_app.solicitudsegurovida'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='camara_app.solicitudsegurovida'),
        ),
    ]
