# Generated by Django 5.2.4 on 2025-07-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0004_declaracionsalud_solicitudsegurovida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionsalud',
            name='cantidad_fumada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='detalle_preguntas_salud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='fuma',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='nombre_medico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta11_salud',
            field=models.BooleanField(default=False, verbose_name='11. ¿Afecciones urinarias o genitales? (riñones, próstata, etc.)'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta12_salud',
            field=models.BooleanField(default=False, verbose_name='12. ¿Enfermedades de la sangre, gota, hernia, etc.?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta13_salud',
            field=models.BooleanField(default=False, verbose_name='13. ¿Enfermedades venéreas o de transmisión sexual?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta14_salud',
            field=models.BooleanField(default=False, verbose_name='14. ¿Accidente grave o intoxicación?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta15_salud',
            field=models.BooleanField(default=False, verbose_name='15. ¿Enfermedades de los oídos?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta16_salud',
            field=models.BooleanField(default=False, verbose_name='16. ¿Enfermedades de los ojos?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta17_salud',
            field=models.BooleanField(default=False, verbose_name='17. ¿Tratamiento por psiquiatra o psicólogo?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta18_salud',
            field=models.BooleanField(default=False, verbose_name='18. ¿HIV o SIDA?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta19_salud',
            field=models.BooleanField(default=False, verbose_name='19. ¿Le han prescrito medicamentos en los últimos 12 meses?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta20_salud',
            field=models.BooleanField(default=False, verbose_name='20. ¿Le han indicado reposo o desintoxicación?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta21_salud',
            field=models.BooleanField(default=False, verbose_name='21. ¿Ha recibido transfusiones?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta22_salud',
            field=models.BooleanField(default=False, verbose_name='22. ¿Le han recomendado no donar sangre?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta23_salud',
            field=models.BooleanField(default=False, verbose_name='23. ¿Tiene capacidad de trabajo reducida?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta24_salud',
            field=models.BooleanField(default=False, verbose_name='24. ¿Ha dejado de trabajar por más de 3 semanas en los últimos 5 años?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta25_salud',
            field=models.BooleanField(default=False, verbose_name='25. ¿Antecedentes hereditarios (diabetes, corazón, etc.)?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta26_salud',
            field=models.BooleanField(default=False, verbose_name='26. ¿Intervención quirúrgica?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta27_salud',
            field=models.BooleanField(default=False, verbose_name='27. ¿Hospitalización pendiente?'),
        ),
        migrations.AddField(
            model_name='declaracionsalud',
            name='pregunta28_salud',
            field=models.BooleanField(default=False, verbose_name='28. ¿Cualquier otra enfermedad no declarada?'),
        ),
        migrations.AddField(
            model_name='deporteactividad',
            name='es_piloto',
            field=models.BooleanField(default=False, verbose_name='¿Es piloto o está en proceso de serlo?'),
        ),
        migrations.AddField(
            model_name='deporteactividad',
            name='paracaidismo',
            field=models.BooleanField(default=False, verbose_name='¿Paracaidismo?'),
        ),
        migrations.AlterField(
            model_name='solicitudsegurovida',
            name='correo_domicilio',
            field=models.CharField(max_length=100, verbose_name='Correo Electrónico Domicilio'),
        ),
        migrations.AlterField(
            model_name='solicitudsegurovida',
            name='correo_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico Trabajo'),
        ),
    ]
