# Generated by Django 5.2.4 on 2025-07-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0005_declaracionsalud_cantidad_fumada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_html', models.CharField(max_length=255)),
                ('subservicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto', to='camara_app.subservicios')),
            ],
        ),
    ]
