# Generated by Django 5.2.4 on 2025-07-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0006_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='id_solicitud',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_html',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='id_subservicios',
        ),
        migrations.AddField(
            model_name='servicios',
            name='id_subservicios',
            field=models.ManyToManyField(blank=True, null=True, related_name='servicios', to='camara_app.subservicios'),
        ),
    ]
