# Generated by Django 5.2.4 on 2025-07-22 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0007_remove_categorias_monto_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioProductoVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_enfermedad_grave', models.BooleanField(default=False)),
                ('ha_sido_hospitalizado', models.BooleanField(default=False)),
                ('practica_deportes_extremos', models.BooleanField(default=False)),
                ('nombre_beneficiario', models.CharField(max_length=100)),
                ('relacion_beneficiario', models.CharField(max_length=50)),
                ('porcentaje_beneficiario', models.PositiveIntegerField()),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_vida', to='camara_app.perfilusuario')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='formulario_vida',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camara_app.formularioproductovida'),
        ),
    ]
