# Generated by Django 5.2.4 on 2025-07-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0008_formularioproductovida_producto_formulario_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='formulario_vida',
        ),
        migrations.AddField(
            model_name='formularioproductovida',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_vida', to='camara_app.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='productos', to='camara_app.perfilusuario'),
        ),
    ]
