# Generated by Django 5.2.4 on 2025-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0011_servicios_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
