# Generated by Django 5.2.4 on 2025-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0012_alter_servicios_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
