# Generated by Django 5.2.4 on 2025-07-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0013_alter_servicios_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='id_servicio',
        ),
        migrations.AddField(
            model_name='categorias',
            name='servicios',
            field=models.ManyToManyField(related_name='categorias', to='camara_app.servicios'),
        ),
    ]
