# Generated by Django 5.2.4 on 2025-07-25 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0014_remove_categorias_id_servicio_categorias_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicios',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
