# Generated by Django 5.2.4 on 2025-07-25 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0015_subservicios_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicios',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
