# Generated by Django 5.2.4 on 2025-07-25 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0015_subservicios_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
