# Generated by Django 5.2.4 on 2025-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0016_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
