# Generated by Django 5.2.4 on 2025-07-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0017_mensaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsegurovida',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
