# Generated by Django 5.2.4 on 2025-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0018_solicitudsegurovida_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='nombre_servicio_a',
        ),
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, related_name='facturas', to='camara_app.producto'),
        ),
    ]
