# Generated by Django 5.2.4 on 2025-07-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0019_remove_factura_nombre_servicio_a_factura_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('archivo_identidad', models.FileField(blank=True, null=True, upload_to='documentos_identidad/')),
                ('archivo_firma', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('firma_generada', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to='camara_app.perfilusuario')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to='camara_app.producto')),
            ],
        ),
    ]
