# Generated by Django 5.2.4 on 2025-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0020_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='archivo_identidad',
            field=models.CharField(help_text='cedula (10 dígitos)', max_length=13, unique=True),
        ),
    ]
