# Generated by Django 5.2.4 on 2025-07-31 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camara_app', '0021_alter_firma_archivo_identidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='archivo_identidad',
        ),
    ]
